### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by whereswaldon** [sternix/wl-scanner#1]
I'm very interested in using Go and Wayland together, and I really appreciate the work that you've done to make that happen. If you have time, could you throw together a README for this that contextualizes this project? I'm not sure exactly what this code is meant to do, except that it has something to do with your `wl` repo (mentioned in the Godoc).

**Comment by sternix** [comment]
Hi @whereswaldon , thank you for interest, i added a simple readme file, i hope i have helped

**Comment by whereswaldon** [comment]
Thanks! So this is the code responsible for generating the bindings in the `wl` repo? I'm curious about why you're playing with Wayland. Are you trying to build anything in particular?

**Comment by sternix** [comment]
Hi @whereswaldon 
> Thanks! So this is the code responsible for generating the bindings in the wl repo?

Of course it's job is read wayland.xml and generate https://github.com/sternix/wl/blob/master/client.go file.

> I'm curious about why you're playing with Wayland. Are you trying to build anything in particular?

i want to write an experimental gui library from scratch with go and wayland but have too many problems, for example go doesn't have full featured draw library like cairo or skia, most gui libraries have low level dependencies like fb , dri , libinput, then i trying efl ( https://www.enlightenment.org/ ) library i liked it, i want to write go binding for efl. now playing with efl, it has complete wayland support.

**Comment by whereswaldon** [comment]
Interesting... I was going to attempt the same thing (making a basic window/gui lib in Go).
Have you seen these? (I imagine that the answer is yes, but I figured that I would check):

 - [draw2d](https://github.com/llgcode/draw2d)
 - [gg](https://github.com/fogleman/gg)

Do you have a start on those efl bindings? I'd be interested to see that.

**Comment by sternix** [comment]
Yes i use draw2d but in X Server and Wayland color codes differs from Go you must convert codes like https://github.com/sternix/wl/blob/master/ui/utils.go#L29
for proper visualization, then try https://github.com/evmar/gocairo but i always faced with C bindings. efl is very lightweight (i write this comment from freebsd 11 + enlightenment), i am playing with efl now, code is not complete and changing, in a near future i can commit my works.
